apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
  namespace: sins
data:
  init.sql: |
    -- Create tables for auth-service
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      username VARCHAR(255) UNIQUE NOT NULL,
      password_hash BYTEA NOT NULL
    );
    ALTER TABLE users OWNER TO "user";

    -- Create table for Snake game scores
    CREATE TABLE IF NOT EXISTS snake_high_scores (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      score INTEGER DEFAULT 0
    );
    ALTER TABLE snake_high_scores OWNER TO "user";

    -- Create table for other game stats (Tic-Tac-Toe and Rock-Paper-Scissors)
    CREATE TABLE IF NOT EXISTS games_stats (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      game_type VARCHAR(50) NOT NULL,
      wins INTEGER DEFAULT 0,
      losses INTEGER DEFAULT 0
    );
    ALTER TABLE games_stats OWNER TO "user";

    -- Give 'user' full rights
    GRANT ALL PRIVILEGES ON TABLE users TO "user";
    GRANT ALL PRIVILEGES ON TABLE snake_high_scores TO "user";
    GRANT ALL PRIVILEGES ON TABLE games_stats TO "user";

    -- Allow access to sequences
    GRANT USAGE, SELECT, UPDATE ON SEQUENCE users_id_seq TO "user";
    GRANT USAGE, SELECT, UPDATE ON SEQUENCE snake_high_scores_id_seq TO "user";
    GRANT USAGE, SELECT, UPDATE ON SEQUENCE games_stats_id_seq TO "user";

    -- Make sure the app user can use the database
    GRANT CONNECT ON DATABASE dbname TO "user";

    -- Make sure the app user can use the public schema
    GRANT USAGE ON SCHEMA public TO "user";

    -- Give full rights on all existing tables
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "user";

    -- Give full rights on all existing sequences
    GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "user";

    -- Ensure future tables/sequences also get these rights automatically
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "user";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "user";
