apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: game-service
  name: gameservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1     #How many extra pods can be deployed
      maxUnavailable: 2 #How many max pods can be deleted
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: game-service
    spec:
      containers:
      - image: aditya090/projectk8s:game
        name: game-service
        ports:
          - containerPort: 8081
        env:
        # Pass database connection info as separate variables
        - name: POSTGRES_HOST
          value: "postgres-rw.sins.svc.cluster.local"
        - name: POSTGRES_DB
          value: "dbname"
        # Fetch credentials securely from the secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"


status: {}
