apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sins
  labels:
    app: frontend-service
  name: frontend-service-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: frontend-service
        image: nginxinc/nginx-unprivileged:stable-alpine   # 👈 safer image
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFileSystem: true
          privileged: false
        volumeMounts:
          - name: cache-volume
            mountPath: /var/cache/nginx   # 👈 writable tmp
      volumes:
        - name: cache-volume
          emptyDir: {}
