apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: sins
  labels:
    app: game-service
spec:
  selector: 
    app: game-service
  ports:
  - name: http-metrics
    port: 8081
    targetPort: 8081
