apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: sins
  labels:
    app: auth-service # <-- Add this label
spec:
  selector: 
    app: auth-service
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
