apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: sins
spec:
  storage:
    storageClass: standard      # or whatever your cluster uses
    size: 5Gi
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  backup:
    barmanObjectStore:
      destinationPath: "s3://bluntaditya/Demo/"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: SECRET_ACCESS_KEY

      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
